Projects/Notes/Sites/Notes/Models/ErrorViewModel.cs
namespace Notes.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Projects/Notes/Sites/Notes/ViewModels/Home/NoteUserViewModel.cs
namespace Notes.ViewModels.Home;

public class IndexViewModel
{
    public NoteUser[]? Users { get; set; }
    
    public class NoteUser
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Age { get; set; }
    }
}

Projects/Notes/Sites/Notes/ViewModels/NoteUser/NoteUserViewModel.cs
namespace Notes.ViewModels.NoteUser;

public class NoteUserViewModel
{
    public int Id { get; set; }
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public int Age { get; set; }
}

Projects/Notes/Sites/Notes/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Notes.Models;

namespace Notes.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Projects/Notes/Sites/Notes/Controllers/NoteUserController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using Core.Interfaces.Services;
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using Notes.ViewModels.Home;
using Notes.ViewModels.NoteUser;

namespace Notes.Controllers;

public class NoteUserController : Controller
{
    private readonly INoteUserService _noteUserService;
    private readonly IMapper _mapper;
    
    public NoteUserController(INoteUserService noteUserService, IMapper mapper)
    {
        _noteUserService = noteUserService;
        _mapper = mapper;
    }

    public async Task<IActionResult> List()
    {
        IndexViewModel model = new IndexViewModel();
        NoteUser[] users = await _noteUserService.GetAllUsersAsync();
        model.Users = _mapper.Map<IndexViewModel.NoteUser[]>(users);
        
        return View(model);
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(NoteUserViewModel model)
    {
        NoteUser noteUser = _mapper.Map<NoteUser>(model);
        await _noteUserService.CreateUserAsync(noteUser);

        return RedirectToAction("List");
    }

    [HttpPost]
    public async Task<IActionResult> Edit(NoteUserViewModel model)
    {
        NoteUser noteUser = _mapper.Map<NoteUser>(model);
        await _noteUserService.UpdateUserAsync(noteUser);

        return RedirectToAction("List");
    }
    
    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        NoteUser? noteUser = await _noteUserService.GetUserById(id);
        NoteUserViewModel model = _mapper.Map<NoteUserViewModel>(noteUser);
        
        return View(model);
    }
}

Projects/Notes/Sites/Notes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<a href="/noteuser/list">Users</a>

Projects/Notes/Sites/Notes/Views/NoteUser/Edit.cshtml
@model Notes.ViewModels.NoteUser.NoteUserViewModel

<form method="POST">
    <div class="form-group">
      <label for="Id">Id</label>
      <input type="text" name="Id" id="Id" class="form-control" value="@Model.Id" readonly>
    </div>
  <div class="form-group">
    <label for="FirstName">First Name</label>
    <input type="text" name="FirstName" id="FirstName" class="form-control" value="@Model.FirstName">
  </div>
  <div class="form-group">
    <label for="LastName">Last Name</label>
    <input type="text" name="LastName" id="LastName" class="form-control" value="@Model.LastName">
  </div>
  <div class="form-group">
    <label for="Age">Age</label>
    <input type="number" name="Age" id="Age" class="form-control" value="@Model.Age">
  </div>
  <div class="form-group">
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

Projects/Notes/Sites/Notes/Views/NoteUser/List.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model Notes.ViewModels.Home.IndexViewModel

</br>

<div class="d-flex justify-content-between">
    <div>
        <button id="refresh-users-btn" class="btn btn-primary">Refresh</button>
        <button id="delete-users-btn" class="btn btn-danger">Delete</button>
    </div>
    <div>
        <a id="create-user-btn" href="@Url.Action("Create", "NoteUser")" class="btn btn-outline-success">Create user</a>
    </div>
</div>

</br>

<div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="w-10" scope="col">#</th>
          <th class="w-60" scope="col">Name</th>
          <th class="w-10" scope="col">Age</th>
          <th class="delete-th w-10" style="display:none" scope="col">Delete</th>
          <th class="w-10" scope="col">Edit</th>
        </tr>
      </thead>
      <tbody id="users">
          @foreach (var user in Model.Users!)
          {
              <tr>
                <td>@user.Id</td>
                <td>@user.Name</td>
                <td>@user.Age</td>
                <td class="delete-th" style="display:none"><input type="checkbox" data-user-id="@user.Id"></td>
                <td><a href="@Url.Action("Edit", "NoteUser", new {id = user.Id})">Edit</a></td>
              </tr>
          }
      </tbody>
    </table>
</div>

Projects/Notes/Sites/Notes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Notes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Notes.styles.css" asp-append-version="true"/>
</head>
<body>
@* <header> *@
@*     <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
@*         <div class="container-fluid"> *@
@*             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Notes</a> *@
@*             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
@*                     aria-expanded="false" aria-label="Toggle navigation"> *@
@*                 <span class="navbar-toggler-icon"></span> *@
@*             </button> *@
@*             <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
@*                 <ul class="navbar-nav flex-grow-1"> *@
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
@*                     </li> *@
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
@*                     </li> *@
@*                 </ul> *@
@*             </div> *@
@*         </div> *@
@*     </nav> *@
@* </header> *@
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

@* <footer class="border-top footer text-muted"> *@
@*     <div class="container"> *@
@*         &copy; 2023 - Notes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
@*     </div> *@
@* </footer> *@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>